### PR TITLE
Article 039: computer scientists confuse halloween

### PR DESCRIPTION
**Pull request by ImarinArwen**
#### Length of text ####
 :page_with_curl: short 

####  Difficulty to read ####
 :mouse:  light 

####  Difficulty to understand #### 

 :mortar_board:  difficult 

####  Type of text #### 
 :laughing:  funny 

####  Type of header #### 
 

 :boom:  catchy

### CODE REVIEW

**Comment by ImarinArwen** [comment]
I don't know how to change the extra "-" in the name of my branch.

**Comment by Teifun2** [comment]
- Please use another word for: "use but it has only two **figures**"
- Check for spelling mistakes.
- "110^3+310^2+310^1+710^0" multiplication symbol missing.
- "Then you string the remainders backwards together." Can be removed or needs to be worded differently
- Please change the number examples to match the title.
- Structure the equations such that it becomes more clear.

This article seems very rough.

**Comment by SimonDold** [comment]
>Please use another word for: "use but it has only two figures"

changed to digits


>"110^3+310^2+310^1+710^0" multiplication symbol missing.

done

>Please change the number examples to match the title.

done (but i think it does not show the concept of the x1 * b^n+x2 * b^(n-1)+x3 * b^(n-2)+...+xn * b^0 so well because they only have two digits)

>"Then you string the remainders backwards together." Can be removed or needs to be worded differently

changed to "Then you string the remainders of these calculations together starting with the one computed last."


>Structure the equations such that it becomes more clear.

i do not know how to do this

>The image is too complex, could you try either explaining the image or simplify it.

The article explains how to get from one system to another, the picture shows the calculations you had to do on the way. It would feel off to me if i added something like "the picture shows the calculations needed this special example"

**Comment by Teifun2** [comment]
We can see the improvements made to this article, but we are unsure if this fits in the book and would like to discuss this article in the plenum for broader opinion.

**Comment by MoiraZuber** [comment]
Suggestion: With preceding article about Counting Systems, this article could be reduced to it's title only.

**Comment by vogti** [comment]
Something is definitely wrong here... It is not possible that an article is part of the final32 and has the archived label at the same time. I am not sure anymore, but if we have agreed in a meeting to archive this article, it should have not been selected as candidate in the final vote. Nevertheless, we did so and the article got a majority of the votes. This means that the majority thinks this article is good and belongs into the final collection. I would therefore argue that we now have a more recent "plenary" vote. According to this vote, I remove the archived label.

**Comment by ImarinArwen** [comment]
Applied grammar changes

**Pull request merged**
