### PR TITLE
Article 052: Patch

### PR DESCRIPTION
**Pull request by tschudin**
#### Length of text ####
:page_with_curl: short

####  Difficulty to read ####
:mouse:  light

####  Difficulty to understand #### 
:school_satchel:  easy

####  Type of text #### 

:bowtie:  informative

####  Type of header #### 
 

:boom:  catchy

### CODE REVIEW

**Comment by Teifun2** [comment]
**Plenum:**
Problems:
- Compare the programm / source code
- Title is long
- Is the article about differences or patches (to loong).

Ideas:
- Title: "Spot the Difference!"
- Title: "Patching is like puzzeling."
- 3rd Image with only the difference?
- Image order?

**Comment by tschudin** [comment]
Der importierte Artikel hat die Kommentare schon aufgenommen, wie folgt:
- Fokus liegt nun auf Patching, nicht Diff
- Drittes Bild mit den Unterschieden dazugefügt, um zu zeigen was zu zeigen ist.
- Reihenfolge ist im Moment (A, B, A-B), d.h. A und B wie bisher. Die eigene Grafik-Umsetzung sollte neu die "Patch"-Reihenfolge umsetzen: B, A, A-B, bzw Buggy, Buggy+Patch, Patch

**Comment by Teifun2** [comment]
Looks good.

**Comment by MoiraZuber** [comment]
Added the new image.

**Comment by Teifun2** [comment]
> Now go and find the differences: Did we spot them all?

We don't think this sentence is required because the difference is clearly visible in the image.

**Comment by tschudin** [comment]
@MoiraZuber : Thanks for the nice pictures!
@Teifun2 : "did we spot them all" is technically not needed, agreed. But it changes the mood, makes it entertaining rather than teaching material (and we have too much of the latter). So I feel we should keep it. Perhaps support the play mood and leave out one element, for example the ice cream ball in the middle image?

**Comment by Teifun2** [comment]
@tschudin We can see your point, it's ok for us to leave it the way it is.

**Comment by tschudin** [comment]
edited as suggested

**Pull request merged**
