### PR TITLE
Article 104: Monte Carlo Methods

### PR DESCRIPTION
**Pull request by SimonDold**
#### Length of text ####
 :page_with_curl: short

####  Difficulty to read ####
:mouse:  light

####  Difficulty to understand #### 

:mortar_board:  difficult

####  Type of text #### 

 :bowtie:  informative

####  Type of header #### 
 

:boom:  catchy

### CODE REVIEW

**Comment by Fjolyo** [comment]
# Plenum Suggestions
- Don't mention Monte Carlo
- Leave out the last paragraph
- The reader is directly addressed 
- Maybe explain "analytical" and "numerical"

**Comment by SimonDold** [comment]
>Don't mention Monte Carlo

I think it is useful to name it in the end, because the reader just learned the concept so the reader can not be scared away anymore by the word. And  the article introduces this concept so it also should tell the name of it.

>Leave out the last paragraph

[see reason above]

>The reader is directly addressed

This is on purpose because YOU (the reader) can do this at home
 
>Maybe explain "analytical" and "numerical"

I changed the wording to "Key is to avoid computing a complicated formula by using random samples in a clever way." to avoid the word analytical

**Comment by SimonDold** [comment]
About the image:

i recommend 28 grains of rice with 22 inside the quatercircle and 6 in the sqaure but outside the circle. Because 22/28 *4 = 22/7 = 3.14286 and 22/7 is a well known approximation of Pi [ https://en.wikipedia.org/wiki/Pi#Approximate_value_and_digits ]

**Comment by Teifun2** [comment]
> I think it is useful to name it in the end, because the reader just learned the concept so the reader can not be scared away anymore by the word. And the article introduces this concept so it also should tell the name of it.

We think this is ok.

> This is on purpose because YOU (the reader) can do this at home

Seems fine.

> I changed the wording to "Key is to avoid computing a complicated formula by using random samples in a clever way." to avoid the word analytical

This makes it easier to understand.


There are still some grammer issues especially in the first sentence.
The rest seems done.

**Comment by Teifun2** [comment]
Add the attributes!

**Comment by MoiraZuber** [comment]
Added the image, no significant changes.

**Comment by noverney** [comment]
-	Maybe say “The ratio of these two numbers approximates the ratio...”
-	Say “Multiply the ratio by 4 and you get Pi, well it is an approximation” 
-	Add a The to the sentence starting with "Key" (it just feels right?)
-	“This is one example of the Monte Carlo Method” (instead of "for the")

**Comment by SimonDold** [comment]
I am happy with the article

**Pull request merged**
