### PR TITLE
Article 036: Moore's Law

### PR DESCRIPTION
**Pull request by kahrpatrick**
#### Length of text ####

:book:  long 

####  Difficulty to read ####

:elephant:  heavy

####  Difficulty to understand #### 

:mortar_board:  difficult

####  Type of text #### 

:bowtie:  informative

####  Type of header #### 
 
:bulb:  informative

### CODE REVIEW

**Comment by kahrpatrick** [comment]
Issues raised in plenum have been addressed as much as possible.

**Comment by Teifun2** [comment]
- Consider reducing the second paragraph. Especially "there is a development towards integrating functions, that until now were provided by separate components, into a single chip." is probably too deep.
- Check our revisions

**Comment by MoiraZuber** [comment]
New image added. I reduced the data points and made it more simple. Also changed the slope slightly to make it better-looking. Can easily be adapted if it is considered too much of a simplification.

**Comment by kahrpatrick** [comment]
Reduced second paragraph and removed dates. Added new ending with outlook to the future of Moore's Law.

**Pull request closed without merging**
