### PR TITLE
Article 007: null

### PR DESCRIPTION
**Pull request by Garcko**
#### Length of text ####
 :page_with_curl: short 

####  Difficulty to read ####
 :mouse:  light 

####  Difficulty to understand #### 
 :school_satchel:  easy 

####  Type of header #### 
 
 :bulb:  informative

### CODE REVIEW

**Comment by Garcko** [comment]
Habe das mit Database und das exist rausgenommen,  Bild habe ich nicht angepasst, da Moira schon das richtige hat

**Comment by MoiraZuber** [comment]
Added image using the proposed idea with the toilet paper.

**Comment by Teifun2** [comment]
> Habe das mit Database und das exist rausgenommen, Bild habe ich nicht angepasst, da Moira schon das richtige hat

We have now removed the last mention of a database. If you are ok with these changes this article can be passed to the testing team.

**Comment by FabricioArendTorres** [comment]
This article has been selected for the Fantasy Basel.


A comment from me for the article:
You could enter a period instead of the comma in the first and last sentence for better readability,
as the sentences can stand on their own.

Also type in 'although' (2nd sentence).

**Comment by Garcko** [comment]
Fixed the typos Fabricio has mentioned and change the first comma to a point. For the last sentence I used semicolon as a compromise

**Pull request merged**
