### PR TITLE
Article 019: The Turing Machine

### PR DESCRIPTION
**Pull request by vogti**
#### Length of text ####

:book:  long

####  Difficulty to read ####

:elephant:  heavy

####  Difficulty to understand #### 

:mortar_board:  difficult

####  Type of text #### 

:bowtie:  informative

####  Type of header #### 
 
:bulb:  informative

### CODE REVIEW

**Comment by Teifun2** [comment]
**Plenum**

Problem:
- Too long
- Missing Alan Turing
- Maybe the workings don't need to be so specific
- Remove State machine
- Last Paragraph , first
- Every sentence starts wit "The Turing..."

Idea:
- Mention finite tape

**Comment by vogti** [comment]
Image idea:
grafik
[Source](https://i0.wp.com/www.worldofcomputing.net/wp-content/uploads/2013/01/turingMachine.gif?resize=400%2C274)

**Comment by MoiraZuber** [comment]
Added the new image according to the suggestion in the plenum.

**Comment by MoiraZuber** [comment]
Could also make it closer to the new image suggestion if desired.

**Comment by vogti** [comment]
Your image is perfect. I really like it :)

**Pull request merged**
