### PR TITLE
Article 100: Errors propagate!

### PR DESCRIPTION
**Pull request by FabricioArendTorres**
#### Length of text ####
 :page_with_curl: short 

####  Difficulty to read ####
:mouse:  light 

####  Difficulty to understand #### 
 :school_satchel:  easy 

####  Type of text #### 

:bowtie:  informative 

####  Type of header #### 
 
 :bulb:  informative 
 :boom:  catchy

### CODE REVIEW

**Comment by FabricioArendTorres** [comment]
Image (obviously) not by me, but the idea should be clear.
Source: https://www.fridayfwd.com/domino-effect/

**Comment by Fjolyo** [comment]
# Plenum Suggestions

- Change "unhoped-for"

- Maybe mention why it is inaccurate

- Maybe drop "scientific" (first sentence second paragraph)

- Maybe make example for exploding inaccuracies

- Maybe add example in the text

**Comment by MoiraZuber** [comment]
Added the new image. No significant changes.

**Comment by FabricioArendTorres** [comment]
I changed the "unhoped for" and "scientific".

I decided against explaining the floating point representation because I'd say it is either incomplete or out of scope for such a small article.

Regarding the example(s): I don't want to change too much of the  text since it was already voted for.

**Comment by noverney** [comment]
- I would jut change "unhoped for results" to "unfortunate results"

**Pull request merged**
