### PR TITLE
Article 123: Dynamic Programming

### PR DESCRIPTION
**Pull request by OmniaKahla**
#### Length of text ####

 :book:  long 

####  Difficulty to read ####
 :mouse:  light 

####  Difficulty to understand #### 
 :school_satchel:  easy 

####  Type of text #### 

 :bowtie:  informative

####  Type of header #### 
 
:bulb:  informative 
 :boom:  catchy

### CODE REVIEW

**Comment by OmniaKahla** [comment]
Changed the article as follows:
- Changed the title to be shorter and does not contain any questions.
- Regarding Fib(x), I have changed the Fibonacci and marked the Fib as bold in the text. 
-  For the last paragraph, it was requested to add 2 or 3 sentences to be easier for the reader to understand the idea not to shorten it.  Now, I changed the 2nd paragraph.

**Comment by OmniaKahla** [comment]
A small addition, it was requested to change the image to add a dotted tree for the parts that have already been calculated. 
Thanks to @MoiraZuber, If you will change it, after the confirmation of the review team.

**Comment by OmniaKahla** [comment]
No problem, but what about the optional text? Is it clear with the optional text or still confusing?

**Comment by MoiraZuber** [comment]
Added the new image. Since the picture would have been very overfilled when going until Fib(5), I stopped at Fib(4), but it could still be extended if desired. Additional suggestion: Handwritten remark pointing at the Fib(2) saying something like "Already computed" might make it easier to understand?

**Pull request closed without merging**
