### PR TITLE
Article 050: Hello World

### PR DESCRIPTION
**Pull request by vogti**
#### Length of text ####
:page_with_curl: short

####  Difficulty to read ####
:mouse:  light

####  Difficulty to understand #### 
:school_satchel:  easy

####  Type of text #### 

:bowtie:  informative

####  Type of header #### 
 

:boom:  catchy

### CODE REVIEW

**Comment by Fjolyo** [comment]
## Plenum Suggestions

- Maybe replace "basic concepts" with "basic flavor"
- Mention that printing text is the easiest interaction

- Image idea: Font -> Typewriter
- Image idea: Multiple babies from different programming languages

**Comment by MoiraZuber** [comment]
Added an image suggestion.

**Comment by Teifun2** [comment]
We like the article and the image. For sake of expediency ee move the article to Grammar and Testing. If the author has some requests according to the image he can mention this.

**Comment by vogti** [comment]
I like the picture.

**Comment by noverney** [comment]
Could replace the following sentence:
Because this is rather simple for nearly all programming languages, it is a good example to see the basic flavor of a programming language.

With: 
Since it is rather easy to write a program to print text, one can familiarize themselves with the basics of a programming in a certain language. 

The reason for the change is you "this" to many times without referring back to what "this" is so by having it restated helps to make it more clear.

**Pull request merged**
