### PR TITLE
Article 033: Brute force

### PR DESCRIPTION
**Pull request by tschudin**
#### Length of text ####

:book:  long

####  Difficulty to read ####
:mouse:

####  Difficulty to understand #### 
:school_satchel:  easy

####  Type of text #### 

:bowtie:  informative

####  Type of header #### 
 

:boom:  catchy

### CODE REVIEW

**Comment by Teifun2** [comment]
**Plenum:**
Problems:
- Image? 
- Dot's seem akward
- Title does not correlate to the image


Ideas:
- Image kicking in the door.
- Keychaing with many keys
- Key lock (trying everything)
- Title : "Brute Force" means you are stupid.

**Comment by tschudin** [comment]
Der importierte Artikel hat die Kommentare schon aufgenommen, wie folgt:
- Bild gewechselt: statt Muskel vs Hochhaus nun der muskulöse Atlas, der die Last von vielen Schlüsseln kaum tragen kann
- weiterhin bei "weak" geblieben, weil jemand Brute Force nicht deshalb wählt weil er/sie "stupid" ist, sondern weil nichts anderes geht. Zudem ist das Bild auf das "weak"-Thema getrimmt (im original wie auch die vorgeschlagene und umgesetzte Aenderung).

**Comment by Teifun2** [comment]
- Dots inside the text look weird and interrupt the reading.
- Image might be to complex and is difficult to interpret. Consider using a combination lock.

**Comment by tschudin** [comment]
* replaced ... with ___
* new image with a gorilla and a combination lock

**Comment by Teifun2** [comment]
> * new image with a gorilla and a combination lock

We like the concept of the new image.

> * replaced ... with ___

We still don't think that this fits. If you would like to keep some sort of spacing we would propose a discussion in the plenum.

**Comment by MoiraZuber** [comment]
Added an image suggestion. I found it very difficult to introduce both the combination lock and something strong (monkey or bodybuilder). I tried it with only the combination lock for now. Would you have any suggestions how to change it?

**Comment by tschudin** [comment]
Thanks @MoiraZuber and @Teifun2 . I suggest to go to the plenum:
- show both image versions (with and without a gorilla)
- bring up the ...

**Comment by Teifun2** [comment]
- Do the dots / underscore with words.
- .. and i really mean every ...

**Comment by tschudin** [comment]
addressed both comments, back to review state.

**Comment by FabricioArendTorres** [comment]
Grammar etc. looks good as is.

**Comment by tschudin** [comment]
adopted the first suggested change,
but not the second one: "weak" should appear in the text otherwise the title is not explained

**Pull request merged**
