### PR TITLE
Article 031: Greedy algorithm

### PR DESCRIPTION
**Pull request by MoiraZuber**
#### Length of text ####

:book:  long

####  Difficulty to read ####
:mouse:  light

####  Difficulty to understand #### 
:school_satchel:  easy

####  Type of text #### 

:bowtie:  informative

####  Type of header #### 
 

:boom:  catchy

### CODE REVIEW

**Comment by Fjolyo** [comment]
## Plenum Suggestions

- Show example that *doesn't* work (Suggestion: train vs. bus for travel)
- (Picture) Meaning of second pile of coins is unclear
- Second paragraph: "most certainly" is too strong, use "most often" instead

**Comment by MoiraZuber** [comment]
Added an mountain climbing example to show when greedy algorithms don't work.
Changed picture to explain this example.
Changed "most certainly not work" to "only work for rather simple problems"

**Comment by Teifun2** [comment]
The greedy path in the image is a little irritating because it does not always takes the "steepest slope" as mentioned in the text. We would either change the text or make a more direct path on the image.

**Comment by MoiraZuber** [comment]
Changed the image. Is it more clear now?

**Comment by MoiraZuber** [comment]
Changed "always taking the steepest slope" to "at every intersection taking the steepest slope" to make the image more fitting.

**Comment by noverney** [comment]
- we don't capitalize after a colon, since it is still considered part of the original sentence (unless it is a proper noun)
- I am curious whether you want to mention that greedy algorithms sometimes do not find the top
Reworking the last sentence:
However, by being greedy you can either miss better opportunities that would bring you to the top faster or end up never reaching the true highest point.

**Pull request merged**
