### PR TITLE
Article 108: Recursion vs. iteration

### PR DESCRIPTION
**Pull request by MoiraZuber**
#### Length of text ####
:book:  long

####  Difficulty to read ####
:elephant:  heavy

####  Difficulty to understand #### 
:mortar_board:  difficult

####  Type of text #### 
:bowtie:  informative

####  Type of header #### 
:boom:  catchy

### CODE REVIEW

**Comment by Teifun2** [comment]
**Plenum:** 
Problems:
- Quite Complex
- Question to the Reader in the first paragraph.

Ideas:
- Say that it is Fibonacci?

**Comment by MoiraZuber** [comment]
Reduced complexity
Kept addressing the reader directly
Tried adding Fibonacci example in text, but it would make the text too long and is already explained in the Recursion article

**Comment by Teifun2** [comment]
- Mention in the image that this is Fibonacci sequence
- This is a difficult topic. We are unsure how to improve. Do you feel confident in the current version or should we pick it up in the Plenum once more?

**Comment by MoiraZuber** [comment]
Corrected image.
Should probably be taken back into the plenum. Might be too difficult and will probably be archived.

**Pull request closed without merging**
