### PR TITLE
Article 086: new version of Y2038, using a time ribbon

### PR DESCRIPTION
**Pull request by tschudin**
####  Difficulty to read ####
:mouse:  light

####  Difficulty to understand #### 
:school_satchel:

####  Type of text #### 

:bowtie:  informative

####  Type of header #### 
 

:boom:  catchy

### CODE REVIEW

**Comment by tschudin** [comment]
@kahrpatrick : I created a new picture, and text, trying to avoid explaining wrap-around, but let the picture see that the bit patterns will repeat. What do you think about this 2038_BIS version?

**Comment by tschudin** [comment]
Not sure about the rules in this Git setup, whether you @kahrpatrick could merge yourself. Feel free to modify the suggested text if you want to pass it to the review team.

**Comment by tschudin** [comment]
Comment to the graphic team @MoriaZuber, in case this picture is approved : 
my intent was to show real time as being fluid, and the UNIX counter as rigid and limited.

**Comment by kahrpatrick** [comment]
I really like this way of approaching the topic! It explains the problem without having to touch the technical details. Highlighting the contrast between "continuous" time and "limited" UNIX time is a good idea.

Some details I observed:
- it may be necessary to point out that UNIX time is commonly used in many operating systems as users might not know what UNIX is
- for better understanding "giving them more bits" could be replaced by "giving them bigger counters"

@tschudin If there are no objections, I would apply the proposed modifications and pass it on to the review team.

**Comment by tschudin** [comment]
@kahrpatrick : glad you like it - yes, please merge into your branch and proceed with your suggested changes so the review team can take over. Fully agreed, UNIX as an operating system is never mentioned and "bigger counters" is what matters.

**Pull request merged**
