### PR TITLE
Article 111: Counting to more than ten with two hands

### PR DESCRIPTION
**Pull request by ImarinArwen**
#### Length of text ####
 :page_with_curl: short 

####  Difficulty to read ####
 :mouse:  light 

####  Difficulty to understand #### 
 :school_satchel:  easy 

####  Type of header #### 
 

 :boom:  catchy

### CODE REVIEW

**Comment by Teifun2** [comment]
**Plenum:**
Problems:
- Word "Significance" could maybe be interchanged (intentionally)
- Hard to know "proper"　orientation of hands in binary counting
- Different numbers (1024)

Ideas:
- Why do the computer only uses only 1 / 0 (power)

**Comment by SimonDold** [comment]
>>Word "Significance" could maybe be interchanged (intentionally)
I kept that because it is a word used in this context (most/least significant bit) and significance is also normally used.

>>Hard to know "proper"　orientation of hands in binary counting
I had to decide on one way, and i chose this one so the thumb is for both hands the less significant bit. And i assume people normaly start counting with their right thumb so it would be fitting.


>>Different numbers (1024)
I changed that. And only that.

>>Why do the computer only uses only 1 / 0 (power)
I think that would overload the last sentence... i either had to kick the one and zero out and replace it with power on power off, but i think the one and zero is important because it is the way you write binary down.
or i add it in brackets
"This is called binary counting and exactly the way a computer counts but with zeros (power off) and ones (power on) instead of bend and stretched fingers."

"This is called binary counting and exactly the way a computer counts but with power off (zeros) and power on (ones) instead of bend and stretched fingers."

both overloads the last sentence in my opinion

**Comment by MoiraZuber** [comment]
Added new image. I reduced it to two hands only to keep it less crowded. Do you think it is still understandable enough?

**Comment by Teifun2** [comment]
This seems ready for testing

**Comment by SimonDold** [comment]
Is now in the survey.

https://www.soscisurvey.de/101tilics/

**Comment by kahrpatrick** [comment]
This article has been selected for Fantasy Basel.

**Comment by FabricioArendTorres** [comment]
- Typo:  'witch' instead of 'which' in the second sentence.
- Grammar/Style: The sentence 'You don't care about which ones are stretched out only the amount of them.' feels clumsy. I think there should at least be a comma. E.g.: 'You don't care about which ones are stretched [out], [but] only [about] the amount of them.'

**Comment by FabricioArendTorres** [comment]
New Typo: The word neighbor is repeated "..the left neighbor neighbor"

**Comment by noverney** [comment]
I reworked what you have written: 

When we use our hands to count, we stretch out a finger one after another. Since the order of the fingers does not matter, we only count the number of stretched out fingers. You can count to 1024 different numbers on your hand if we assign the value of 1 to the right thumb and from right to left double the value of each preceding finger. 1+2+4+8+16+32+64+128+256+512=1023 and 0. This is called binary counting and is exactly the way a computer counts but with zeros and ones instead of bent and stretched fingers.

**Comment by SimonDold** [comment]
I used 'you' intentionally to speak to the reader. 

I want to keep this sentece "Each of them is as significant as the other" because everyone knows THAT the order does not matter but this explains WHY the order does not matter.

I want to keep the word 'significant' because it is also used in (MSB/LSB: Most/Least Significant Bit)

"You can count to 1024 different numbers on your hand if we assign the value of 1 to the right thumb and from right to left double the value of each preceding finger."
Telling the result (can count to 1024) and after that how to it (by assign values this way) feels less exitic for me.

the effect is probably stronger in an example like this:
"In a dark night Jack used his old hunting knife to kill his mother."
vs
"Jack killed his mother by using his old hunting knife in a dark night."

**Pull request merged**
