### PR TITLE
Article 086: year 2038 problem

### PR DESCRIPTION
**Pull request by kahrpatrick**
#### Length of text ####
 :page_with_curl: short 

####  Difficulty to read ####
 :mouse:  light

####  Difficulty to understand #### 
 :school_satchel:  easy

####  Type of text #### 

 :bowtie:  informative

####  Type of header #### 
 

:boom:  catchy

### CODE REVIEW

**Comment by Teifun2** [comment]
Seems good.
Image is maybe too informative, but in general very good.

**Comment by Fjolyo** [comment]
## Plenum Suggestions

- Negative numbers might be unclear
- *Signed* bit is technically not correct
- Big overlapp with Overflow article
- Might move to archive?

**Comment by kahrpatrick** [comment]
Merged new version of article proposed by @tschudin. Applied changes discussed in pull-request https://github.com/unibas-tilics/tilics/pull/51. 
It approaches the topic in a way that negative numbers don't have to be explained any more. This addresses the two first points of concern of the audience. 
The overflow is still mentioned, but not as central any more, reducing the overlap with the Overflow article. This addresses the third point of concern.

**Comment by Fjolyo** [comment]
Looks much better, the article is still quite long, but we think this is okay.
We don't know if the image fits the article well, but maybe @MoiraZuber can make a shorter/clearer version of it.

**Comment by MoiraZuber** [comment]
Added an image suggestion. Any thoughts?

**Pull request merged**
