### PR TITLE
Article 038: Turing Test

### PR DESCRIPTION
**Pull request by vogti**
#### Length of text ####
:page_with_curl: short

####  Difficulty to read ####
:mouse:  light

####  Difficulty to understand #### 
:school_satchel:  easy

####  Type of text #### 
:laughing:  funny

####  Type of header #### 
 

:boom:  catchy

### CODE REVIEW

**Comment by Teifun2** [comment]
Plenum:
- Is the Turing Test really already achieved?
- Twist with recognizing man vs. woman
- Intelligence is perceptive. If we think they are intelligent, they are?

**Comment by MoiraZuber** [comment]
Added the new image according to the suggestion in the plenum ("I'm not a robot").

**Comment by Teifun2** [comment]
Image is nice.

> chat support of your **ISP** tries to calm

We would assume that not everybody understands this. Either write it out or make another example.

**Comment by vogti** [comment]
I changed "ISP" to "telecom company"

**Comment by noverney** [comment]
Change:
If not, how you find out?
To:
If not, how would you find out?
-	Do we really need “, a long time before the first online stores opened,” ?
Suggested Edit as well as reworking the sentence: 
In 1950, a computer science pioneer named Alan Turing  invented the Turing test to determine whether someone was a robot.

**Comment by vogti** [comment]
To say "... invented the Turing test to determine whether someone was a robot." would not be 100% correct. I have now combined your suggestion with my previous sentence.

**Pull request merged**
