### PR TITLE
Article 121: Quine

### PR DESCRIPTION
**Pull request by tschudin**
#### Length of text ####
:page_with_curl: short

####  Difficulty to read ####
:mouse:  light

####  Difficulty to understand #### 
:school_satchel:  easy

####  Type of text #### 

:bowtie:  informative

####  Type of header #### 
 

:boom:  catchy

### CODE REVIEW

**Comment by Teifun2** [comment]
**Plenum:**

Problems:
- Quine quote signs are different
- Maybe say that is not especially useful

Ideas:
- Image could be robot building itself

**Comment by MoiraZuber** [comment]
Added the new image corresponding to the idea from the plenum. I think the image is too abstract without a quick explanation in the text. Maybe just a term such as "building another version of itself" is needed.

**Comment by tschudin** [comment]
- quotes are fixed
- nice picture - which is now explained in the last sentence.
The 'not very useful' comment is obsolete in the sense that for these robots, Quines are essential.

**Comment by Fjolyo** [comment]
Looks good! Moved to grammar

**Comment by FabricioArendTorres** [comment]
I already looked at the grammar.. Not sure which label to use now

**Comment by SimonDold** [comment]
is now on the soscisurveyfor testing

**Comment by noverney** [comment]
- the changes below add clarity but are not necessary 
Change:
It’s not that easy – even a versed programmer will spend some hours to figure out the trick (which can be different for each programming language).
To:
It’s not that easy – even a well-versed programmer will need to spend some hours to figure out the trick (which can be different for each programming language).

- using this and that is when we don't have the word we are describing. Since we have "self-description" already there we can use "the". Starting with "and" is a bit controversial but I am not removing it because it looks weird but it seems to imply that it is another trick. 
Change:
And because outputting that self-description also needs code, this self-description
must be somehow compressed.
To: 
Because outputting the self-description also needs code, the self-description must be somehow compressed.

**Comment by tschudin** [comment]
edited according to the suggestions, thanks
added '--' and parentheses, though

**Comment by Teifun2** [comment]
Looks good

**Pull request merged**
