### PR TITLE
Article 010: Mincing Bytes (or the Art of Hashing)

### PR DESCRIPTION
**Pull request by tschudin**
#### Length of text ####
:page_with_curl: short

####  Difficulty to read ####
:mouse:  light

####  Difficulty to understand #### 
:school_satchel:  easy

####  Type of text #### 

:sunglasses:  catchy

####  Type of header #### 
 

:boom:  catchy

### CODE REVIEW

**Comment by Fjolyo** [comment]
# Plenum Suggestions

- Idea not clear for a beginner
- Change "meticulously"
- Last sentence is confusing, answer WHY it is important for data management
- First sentence of second paragraph is too complex
- Mention collision between hashes

**Comment by tschudin** [comment]
Ah, perhaps this article can be saved, after all! I think I was able to address all concerns. Back to review state.

**Comment by MoiraZuber** [comment]
Added the new image. Tried to keep it close to the suggested image.

**Comment by tschudin** [comment]
thank you, @MoiraZuber !

**Comment by Fjolyo** [comment]
Article feels too long and maybe too diverse.

We think the last paragraph can be left out.

**Pull request closed without merging**
