### PR TITLE
Article 079: Why do programmers need forks?

### PR DESCRIPTION
**Pull request by kahrpatrick**
#### Length of text ####
 :page_with_curl: short

####  Difficulty to read ####
:mouse:  light

####  Difficulty to understand #### 
 :school_satchel:  easy 

####  Type of text #### 

 :bowtie:  informative

####  Type of header #### 
 

:boom:  catchy

### CODE REVIEW

**Comment by Fjolyo** [comment]
## Plenum Suggestions

- (Picture) Circles might not be needed. Make it more clear that they are *different* now and won't merge
- Maybe mention "forking" is an "honor" for the original

**Comment by MoiraZuber** [comment]
Added an image suggestion including the example with the houses. Do you think this makes sense, or do you have another suggestion? Also the descriptions "original project" and the "forked project" could still be added if desired.

**Comment by kahrpatrick** [comment]
Picture looks very good! I didn't change the text as it is short and self-contained. Mentioning the 'honour' of forking would need a broader discussion.

**Comment by Fjolyo** [comment]
Looks good! Moved to grammar.

**Comment by noverney** [comment]
- you can drop that comma after "Programmers, engineers, and users,"

**Comment by kahrpatrick** [comment]
There is nothing more to do here.

**Pull request merged**
