### PR TITLE
Article 032: Deadlock

### PR DESCRIPTION
**Pull request by kahrpatrick**
#### Length of text ####

:book:  long

####  Difficulty to read ####

:elephant:  heavy

####  Difficulty to understand #### 
:school_satchel:  easy

####  Type of text #### 

:bowtie:  informative

####  Type of header #### 
 
:bulb:  informative

### CODE REVIEW

**Comment by Teifun2** [comment]
**Plenum:**
Problems:
- P1 etc. (Complicated?)


Ideas:
- 4 Cars for circular waiting
- Dining Philosophers

**Comment by kahrpatrick** [comment]
Problem 'P1 etc. (Complicated?)' addressed by removing with simpler expression. Figure changed to 4 waiting cars to make the situation easier to understand. Dining philosophers is a nice idea, but cars are easier to relate to IMHO.

**Comment by MoiraZuber** [comment]
Added new image. I think only one intersection is enough to convey the concept, two would maybe be too crowded?

**Comment by Teifun2** [comment]
> Dining philosophers is a nice idea, but cars are easier to relate to IMHO.

We agree!

Please revise:
- The third paragraph could be removed completely or reduced dramatically as it does not help to understand the problem. Explaining possible solutions is too advanced in our opinion.
- @MoiraZuber In our opinion the cars should stand behind the imaginary "stoplines". The current scenario could not even be resolved with hand signs.

**Comment by MoiraZuber** [comment]
Changed the picture accordingly.

**Comment by kahrpatrick** [comment]
>     * The third paragraph could be removed completely or reduced dramatically as it does not help to understand the problem. Explaining possible solutions is too advanced in our opinion.
> 

Good idea. I removed the discussion.

**Comment by Fjolyo** [comment]
> Good idea. I removed the discussion.

The article looks done to us.

**Comment by OmniaKahla** [comment]
grammar has been updated.

**Comment by kahrpatrick** [comment]
Thank you for the grammar review @OmniaKahla @FabricioArendTorres! I have a comment regarding the pronoun "their" in the second sentence that you changed to "his". In terms of grammar there was nothing wrong here. It is not a plural, but a so-called "singular they" (https://en.wikipedia.org/wiki/Singular_they) that has been used in the English language for a long time. Nowadays it is used in contexts where the gender of a person - in our case the driver - is not clear. It is up to you which option you chose for the articles in this book. I will continue to used it for the sake of a gender-neutral expression that includes all people.

**Pull request merged**
