### PR TITLE
Article 083: Being lazy is a good thing

### PR DESCRIPTION
**Pull request by vogti**
#### Length of text ####

:book:  long

####  Difficulty to read ####
:mouse:  light

####  Difficulty to understand #### 
:school_satchel:  easy

####  Type of text #### 
:laughing:  funny

####  Type of header #### 
 

:boom:  catchy

### CODE REVIEW

**Comment by Teifun2** [comment]
**Plenum:**
Problems:
- To many goods.
- Title not too good. (Could also mean lazy search)
- We are more smart then lazy.

Idea:
- Automation is a lot of work.

**Comment by MoiraZuber** [comment]
Added new image. Reduced the comic to the last panel, because I thought it would be sufficient.

**Comment by vogti** [comment]
I had again a look at the article and the suggested improvements:

> To many goods.
In the article I have used the word "good" five times. The problem is, that I am not aware of good synonym for "good" in this context. There a a few words which go into the same direction, e.g. "competent", "skilled" and "excellent". But I think none of these really fit in this article. Do you know a good word?

> Title not too good. (Could also mean lazy search)
There are also other things with "lazy", e.g. "lazy replication" or "lazy evaluation". I think that every (especially every catchy title) can be misunderstood. I can change the title if you think that the possible confusion should be fixed in favor of a not so catch title.

> We are more smart then lazy.
This is what the article is about. We make things more efficient, we implement generic solutions, strategically lazy and so on. 

> Automation is a lot of work.
Yes. I tried to integrate that aspect with "Good programmers are diligent to be lazy." Do you think it needs more than that?

**Comment by FabricioArendTorres** [comment]
This article has been selected for Fantasy Basel.

**Comment by vogti** [comment]
I have applied the comments of Normand.

**Comment by FabricioArendTorres** [comment]
Grammar looks fine as is.

**Pull request merged**
