### PR TITLE
Article 023: FLOPS

### PR DESCRIPTION
**Pull request by Fjolyo**
#### Length of text ####
:page_with_curl: short

####  Difficulty to read ####
:mouse:  light

####  Difficulty to understand #### 
:school_satchel:  easy

####  Type of text #### 

:bowtie:  informative

####  Type of header #### 
 

:boom:  catchy

### CODE REVIEW

**Comment by MoiraZuber** [comment]
Added an image suggestion. Changed it a lot from the authors suggestion. Review required.

**Comment by Teifun2** [comment]
We don't know how to improve the article, but we are unsatisfied with its quality. Could you give us some input or is this maybe a case for the archive?

**Comment by marcelluethi** [comment]
@Fjolyo  @Teifun2 Before starting a formal review of the article, here my personal opinion on the article: 
I like the comparison with the brain (and the image) a lot and think this is interesting. Maybe one possibility to improve it would be to make it less technical, and instead to focus even more on the comparison. One could remove the sentences "A floating point operation describes a mathematical procedure using decimal numbers. " as well as the last sentence. Not sure if it would be necessary in this case to add a sentence to explain, that the brain gets its power from being massively parallel. 

What do you think?

**Comment by MoiraZuber** [comment]
Added corrected image.

**Comment by marcelluethi** [comment]
@Teifun2  Do you have any comments regarding my last review comment? How should we proceed here?

**Comment by Fjolyo** [comment]
> @Teifun2 Do you have any comments regarding my last review comment? How should we proceed here?

We noticed just now that you made a suggestion, since the label wasn't changed.
We will have a look at it soon.

**Comment by marcelluethi** [comment]
@Teifun2  Yes, I did not change it to revise, because I just wanted your opinion. But I perfectly understand that my comment got lost in a sea of github notifications. Always happens to me as well 😃

**Comment by Teifun2** [comment]
We would like to archive this article for the time being, and focus on more polished articles..

**Pull request closed without merging**
