### PR TITLE
Article 091: bayes theorem

### PR DESCRIPTION
**Pull request by FabricioArendTorres**
#### Length of text ####

:book:  long

####  Difficulty to read ####
:mouse:  light

####  Difficulty to understand #### 
:school_satchel:  easy

####  Type of text #### 

:bowtie:  informative

####  Type of header #### 
 
:bulb:  informative

### CODE REVIEW

**Comment by FabricioArendTorres** [comment]
I changed the poker example to a dice example.
I think Yahtzee should be well known, but if someone has a better idea I'm open for that.

However, I still can't think of a proper image..

**Comment by Teifun2** [comment]
**Plenum:**
Problems:
- Sentence "Notion of faces" is difficult to understand
- Maybe only one example (is addressed as stated by the author)


Idea:
- Using Cheating in title or in article
- Maybe use a bayesian example that could surprise the audiance (is addressed as stated by the author)

**Comment by Teifun2** [comment]
Please revise:
- Consider changing / reducing the last paragraph paragraph, in our opinion it's a tad too long.
- Do you have any idea for the picture? Bayesian formula?

**Comment by MoiraZuber** [comment]
Added an image proposal, five dice showing the same number on top. An additional idea would be to make the dice look crooked somehow, but I found it difficult to add and left it for now.

**Comment by FabricioArendTorres** [comment]
1. Removed one sentence from the last paragraph, I hope that is sufficient. I'd really like to keep the last sentence because that is in my opinion an important part.

2. Thanks @MoiraZuber for the image

Other:
Changed second to last sentence, now it should be a bit easier to read.

**Comment by OmniaKahla** [comment]
grammar has been updated.

**Comment by FabricioArendTorres** [comment]
Grammar changes were minor / did not affect the text -> I'll directly switch it to test

**Pull request closed without merging**
