### PR TITLE
Article 114: Why Uptime Matters

### PR DESCRIPTION
**Pull request by s3lph**
#### Length of text ####

:book:  long

####  Difficulty to read ####

:elephant:  heavy

####  Difficulty to understand #### 
:school_satchel:  easy

####  Type of text #### 

:bowtie:  informative

####  Type of header #### 
 

:boom:  catchy

### CODE REVIEW

**Comment by Teifun2** [comment]
**Plenum:**

Problem:
- What implication does it have if a hardware server is down
- Rather long
- More bold (server / service)

Idea:
- Split server / service discussion

**Comment by s3lph** [comment]
I tried to implement the feedback. I'm not too happy with the result yet, though.

**Comment by MoiraZuber** [comment]
Added an image suggestion. Any thoughts?

**Comment by s3lph** [comment]
I like the unplugged robot, but I don't understand what the table with the drinks is supposed to show.

**Comment by MoiraZuber** [comment]
A better idea came up. What about this one?

**Comment by s3lph** [comment]
I'd rather leave it at "we want it to be available at all times.", as it stresses the "at all times" part more. I agree with the change from "has to" to "must", though.

**Pull request merged**
