### PR TITLE
Article 030: Big O Notation

### PR DESCRIPTION
**Pull request by MoiraZuber**
#### Length of text ####

:book:  long

####  Difficulty to read ####
:mouse:  light

####  Difficulty to understand #### 
:school_satchel:  easy

####  Type of text #### 

:sunglasses:  catchy

####  Type of header #### 
 

:boom:  catchy

### CODE REVIEW

**Comment by Fjolyo** [comment]
# Plenum Suggestions:
- Mention upper bound
- Maybe talk about exponential or other complexities (Maybe talk about it in another article)
- Should the article be about "scalability" instead? ("Does it scale?")

**Comment by MoiraZuber** [comment]
Changed the focus to scalability instead of big O notation. Upper bound and other complexities are therefore not relevant anymore.

**Comment by Teifun2** [comment]
> Changed the focus to scalability instead of big O notation. Upper bound and other complexities are therefore not relevant anymore.

Looks good!

**Comment by MoiraZuber** [comment]
Added the final image.

**Comment by noverney** [comment]
- I am assuming you are using the British English for spelling analyze
- you have a nicely written example but I am bit confused what you are implying. Are you saying that 1000 movies would still take one shipment? Are you also implying that we can only sequentially download the movies? 
- I would suggest saying that: the truck can only store so many movies while you could easily scale by adding more storage space with more hard drives, a truck cannot get suddenly bigger.

**Comment by MoiraZuber** [comment]
- Should I change it to American English?
- The example should be as simple as possible, so I didn't want to include parallelism. It should only show that one method depends on the number of movies, the other doesn't. I changed the number so that it is more realistic.

**Comment by vogti** [comment]
I think it makes sense that we try to be consistent in spelling. I would therefore suggest that you change the spelling to American English.

**Comment by MoiraZuber** [comment]
Changed spelling to American English.

**Pull request merged**
