### PR TITLE
Article 013: Exclusive OR

### PR DESCRIPTION
**Pull request by vogti**
#### Length of text ####

:book:  long

####  Difficulty to read ####
:mouse:  light

####  Difficulty to understand #### 
:school_satchel:  easy

####  Type of text #### 

:bowtie:  informative

####  Type of header #### 
 
:bulb:  informative

### CODE REVIEW

**Comment by MoiraZuber** [comment]
Added image with no significant changes.

**Comment by vogti** [comment]
I added a sentence that "or" is also called "inclusive or".

**Comment by kahrpatrick** [comment]
This article has been selected for Fantasy Basel.

**Comment by FabricioArendTorres** [comment]
I think it should be _an_ instead of _a_ in:
- _'The question whether a**n** "or" [..]'_
- _'In English, we can express a**n** XOR [..]'_  (not totally sure about this one)

**Comment by vogti** [comment]
Thank you. You are right.
I checked in the englisch wikipedia. They always use a**n** XOR, so I fixed both.

**Comment by marcelluethi** [comment]
@vogti 
The rule is really simple, but not widely known. Whenever when the word starts with a vowel when you *pronounce* it (not write it) it is preceded by an *an*.  So since XOr is pronounced as EX-Or, it should be an *an*.

**Comment by Teifun2** [comment]
> either … or 
We would propose with quotation marks: "either ... or ..."

The first sentence is a little confusing. Maybe replacing the "and" with "both" could help?

The third paragraph could maybe be shortened and incorporated in to the second one, as it contains quite some overlaps.

**Comment by vogti** [comment]
Thank you very much for the comments.

The "either ... or ..." is a very good idea. I have changed that. I furthermore added an "also" in the first sentence. Maybe that helps to understand this sentence.

I've been thinking of your suggestion to use "both" instead of "and" in the first sentence, but I think that makes the sentence more confusing, as "both" does not really work as a substitute for "and". But I have "both" in the last sentence of the article.

The only thing which I see that can be shortened is "It is therefore also called "inclusive or"". However, this was proposed by the plenum. Do you see something specific that can be shortened?

I do not think that there is much overlap between these two paragraphs. The second introduces the two terms while the third explains them.  Furthermore, without shortening the second paragraph, the resulting paragraph would be quite long which makes it harder to read.

**Pull request merged**
