### PR TITLE
Article 109: world of triangles

### PR DESCRIPTION
**Pull request by ImarinArwen**
#### Length of text ####
:page_with_curl: short 

####  Difficulty to read ####
:mouse:  light 

####  Difficulty to understand #### 
 :school_satchel:  easy

### CODE REVIEW

**Comment by Teifun2** [comment]
**Plenum：**
Problems:
- Everyone sees Images as Pixel.
- Visualization is still done with pixels / representation
- "Smooth areas like a cube"
- Why do we use trinagles


Ideas:
- Grapics half "rendered" / half "triangles"

**Comment by ImarinArwen** [comment]
I have added the explanation that points of triangles are on the same plane.
And I changed the smooth to a  simple object with flat surfaces like a cube".
I'm not sure whether I should mention the pixel-thing. I guess the article gets too long then. What do you think?

**Comment by MoiraZuber** [comment]
Added new image with no significant changes. The idea of having the pot half rendered was difficult to realize, so I let it away for now. I could still try it if it is wished.

**Comment by Teifun2** [comment]
This article is ready for Testing.

> I'm not sure whether I should mention the pixel-thing. I guess the article gets too long then. What do you think?
We agree!

> Added new image with no significant changes. The idea of having the pot half rendered was difficult to realize, so I let it away for now. I could still try it if it is wished.
We don't think this is necessary.

**Comment by SimonDold** [comment]
Is now in the survey.

https://www.soscisurvey.de/101tilics/

**Comment by FabricioArendTorres** [comment]
- Grammar: _"To visualize a surface a set of those points are connected by lines."_
1. A set is singular (so _is_ instead of _are_) and I think a comma is missing:
_"To visualize a surface**,** a set of those points **is** connected by lines."_
2. I'd say an article (**a**) is missing: 
_" The mathematical figure which emerges through this process is called **a** polygon."_
3. Missing comma: (see https://www.grammar-quizzes.com/themore.html )
_"The more triangles are used**,** the more detailed a surface is."_
4. It should be _whereas_ or _while_ instead of _where_, since it is used to contrast 2 things.
_"**Whereas** a simple object with flat surfaces like a cube can be modeled by using only a few triangles, for a more complex structure like a teapot, many more triangles are required to represent its round shape."_ 

- Style suggestion from me:
The last sentence is pretty difficult to read, maybe:
_"Whereas a simple object with flat surfaces like a cube can be modeled by using only a few triangles, a more complex structure like a teapot requires many more triangles for [representing] its round shape."_

**Comment by SimonDold** [comment]
i think "3D" should be added somewhere in the first sentence, because cartoons/southpark for example are also computer animated but 2D and therefor not made of triangles

**Comment by ImarinArwen** [comment]
I changed the grammar and added 3D.

**Comment by ImarinArwen** [comment]
Added an of after comprises

**Pull request merged**
