### PR TITLE
Article 076: Always use a VCS

### PR DESCRIPTION
**Pull request by FabricioArendTorres**
#### Length of text ####
 :page_with_curl: short 

####  Difficulty to read ####
:mouse:  light 

####  Difficulty to understand #### 
 :school_satchel:  easy 

####  Type of text #### 
 :bowtie:  informative

####  Type of header #### 
 :bulb:  informative

### CODE REVIEW

**Comment by FabricioArendTorres** [comment]
- _"Remove the 'cloud storage'":_ I got rid of mentioning storage entirely and focused on the multiple files with different names.
- _"Focus more on versioning"_: I don't really want to make the article bigger, so instead tried to put the focus on the versioning in the second to last sentence.
- _"Change the word 'merging'":_ Done, now combined

**Comment by Teifun2** [comment]
**Plenum:**
Problems:
- Merge is to difficult (comibine?)
- Do not use cloud storage in the beginning.


Ideas:
- Image: with final, final_final, real_final, _v2, _v3 etc.
- Is VCS a backup?
- Title could be done differently / maybe also not.
- Trivia is good.

**Comment by Teifun2** [comment]
Please reupload with branch name according to guidelines.

**Comment by Teifun2** [comment]
Please revise the last sentence. The phrasing with "at the time" is confusing to read.
Please also add the attributes to the Pull Request.

**Comment by Teifun2** [comment]
> * _"Remove the 'cloud storage'":_ I got rid of mentioning storage entirely and focused on the multiple files with different names.

Looks good.

> * _"Focus more on versioning"_: I don't really want to make the article bigger, so instead tried to put the focus on the versioning in the second to last sentence.

Seems fair.

> * _"Change the word 'merging'":_ Done, now 'combine'

Looks good.


This article seems done!

**Comment by MoiraZuber** [comment]
Added the image. Changed the content slightly.

**Comment by MoiraZuber** [comment]
Issues with the font in the image. Will be revised.

**Comment by MoiraZuber** [comment]
Added the corrected image.

**Comment by SimonDold** [comment]
is now on the soscisurveyfor testing

**Pull request merged**
